name: Rust Tauri Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Rust
        uses: actions/setup-rust@v2

      - name: Build Tauri App
        run: |
          cargo install tauri-bundler
          cargo tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sqlite-viewer-linux
          path: target/sqlite-viewer-build
